%% Import data from text file.
% Script for importing data from the following text file:
%
%    /home/houjebek/paparazzi/sw/tools/ram_logger/build/log_flight3.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2018/01/07 19:47:57

%% Initialize variables.
%filename = '/home/houjebek/Desktop/CX10data/log_flight3.csv';
% filename = '/home/houjebek/Desktop/CX10data/log_static.txt';
% filename = '/home/houjebek/Desktop/CX10data/log_static2.txt';
% filename = '/home/houjebek/Desktop/CX10data/log_spinupdown2motor2.csv';
% filename = '/home/houjebek/Desktop/CX10data/log_lpf05_thrt.csv';
filename = '~/paparazzi/sw/tools/ram_logger/build/log.csv';
delimiter = ',';

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'TextType', 'string', 'EmptyValue', NaN,  'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
logflight3 = table(dataArray{1:end-1}, 'VariableNames', {'AccX','AccY','AccZ','GyroX','GyroY','GyroZ'});

%% Clear temporary variables
clearvars filename delimiter formatSpec fileID dataArray ans;

%%
figure;
subplot(3,2,1);plot(logflight3{:,1}*(1/9810));legend('accX')
subplot(3,2,3);plot(logflight3{:,2}*(1/9810));legend('accY')
subplot(3,2,5);plot(logflight3{:,3}*(1/9810));legend('accZ')

subplot(3,2,2);plot(logflight3{:,4}*(1/9810));legend('gyroX')
subplot(3,2,4);plot(logflight3{:,5}*(1/9810));legend('gyroY')
subplot(3,2,6);plot(logflight3{:,6}*(1/9810));legend('gyroZ')

figure;

subplot(3,1,1);plot( filter(ones(100,1)/100,1,logflight3{:,1}*(1/9810)));
hold on
plot(logflight3{:,6}/max(logflight3{:,6}))
legend('Filtered accX [g]', 'Throttle')

subplot(3,1,2);plot( filter(ones(100,1)/100,1,logflight3{:,2}*(1/9810)));
hold on
plot(logflight3{:,6}/max(logflight3{:,6}))
legend('Filtered accY [g]', 'Throttle')

subplot(3,1,3);plot( filter(ones(100,1)/100,1,logflight3{:,3}*(1/9810)));
hold on
plot(logflight3{:,6}/max(logflight3{:,6}))
legend('Filtered accZ [g]', 'Throttle')

